baseURL =  'http://blog.nalluru.com/'
languageCode = "en-us"
title =  'Blog of Suresh Kumar Nalluru'

theme = [ "my",  "hugo-ink" ]

copyright = "Â© 2012-2021 Suresh Kumar Nalluru. All rights reserved"
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disableLiveReload = false
canonifyurls = true
paginate = 10

[permalinks]
    # if the slug is not present, this takes the value of title of the page
  #post = "/:slug/"
  post = "/:section/:year/:month/:slug/"

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
    dateFormat = "02 Jan 2006, 15:04"
	mode = "auto" # "dark" or "auto"
    featherIconsCDN = true

#without this subtitle, the social icons seem to be weirdly placed
	subtitle = ""

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nasuku"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"
